name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install cmake

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake

      - name: Configure Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: cmake -B build

      - name: Build Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: cmake --build build

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release
