name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Windows - Install Dependencies
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            make

      - name: Linux - Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev

      - name: Windows - Configure
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: cmake -B build
      
      - name: Linux - Configure
        if: runner.os == 'Linux'
        run: cmake -B build

      - name: Windows - Build
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: cmake --build build

      - name: Linux - Build
        if: runner.os == 'Linux'
        run: cmake --build build --config Release
      
      - name: Prepare package
        run: |
          mkdir package
          cp build/bin/* package/
          cp -r assets package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mts26-${{ runner.os }}-0.1.0
          path: package/  
